### ISSUE TITLE
MHN Server Install Error with docker

### ISSUE THREAD

**Issue by laputa1312** [pwnlandia/mhn#532]
Successfully installed Beaker-1.6.4 Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 Sphinx-1.2.3 WebOb-1.7.4 WebTest-2.0.16 beautifulsoup4-4.6.0 bottle-0.13.dev0 bottle-cork-0.6 bottle-mongodb-0.2.1 certifi-2018.1.18 chardet-3.0.4 docutils-0.14 gevent-1.0.2 greenlet-0.4.13 hpfeeds-threatstream idna-2.6 kumo-0.2 nose-1.3.4 pycrypto-2.6.1 pymongo-2.7.2 python-magic-0.4.6 requests-2.18.4 six-1.11.0 sphinxcontrib-httpdomain-1.3.0 urllib3-1.22 waitress-1.1.0
+ chmod 755 -R .
+ IDENT=mnemosyne
++ python -c 'import uuid;print str(uuid.uuid4()).replace("-","")'
+ SECRET=a13595be017545189ecebd89cf2ebb77
+ CHANNELS=amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,cowrie.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events,elastichoney.events
+ cat
+ deactivate
+ unset -f pydoc
+ '[' -z _ ']'
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ export PATH
+ unset _OLD_VIRTUAL_PATH
+ '[' -z '' ']'
+ '[' -n /bin/bash ']'
+ hash -r
+ '[' -z _ ']'
+ PS1=
+ export PS1
+ unset _OLD_VIRTUAL_PS1
+ unset VIRTUAL_ENV
+ '[' '!' '' = nondestructive ']'
+ unset -f deactivate
+ . /opt/hpfeeds/env/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/opt/hpfeeds/env
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
++ PATH=/opt/hpfeeds/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /opt/hpfeeds/env
++ PS1='(env) '
++ export PS1
++ alias pydoc
++ '[' -n /bin/bash ']'
++ hash -r
+ python /opt/hpfeeds/broker/add_user.py mnemosyne a13595be017545189ecebd89cf2ebb77 '' amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,cowrie.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events,elastichoney.events
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/add_user.py", line 29, in <module>
    res = client.hpfeeds.auth_key.update({"identifier": ident}, {"$set": rec}, upsert=True)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 2968, in update
    write_concern, collation=collation)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/collection.py", line 835, in _update_retryable
    _update, session)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1098, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1404, in _tmp_session
    s = self._ensure_session(session)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1391, in _ensure_session
    return self.start_session(causal_consistency=False)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1369, in start_session
    server_session = self._get_server_session()
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1377, in _get_server_session
    return self._topology.get_server_session()
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/topology.py", line 416, in get_server_session
    None)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

I am using Centos 7 to install MHN, I try several time to install. the result is same.
Also I try to install in ubuntu 16.04, it still occur this error. 
may I know what problem or what step I miss?

**Comment by freegit9527** [comment]
I used  centos6.9 to install MHN  with docker , and it come  to the same error.

**Comment by tr4cefl0w** [comment]
That's because Docker containers don't have systemd. Edit the Dockerfile to install mongodb and then execute this command:
/usr/bin/mongod --fork --logpath /var/log/mongodb/mongod

before ./install.sh is launched
