### ISSUE TITLE
No MHN services after installation

### ISSUE THREAD

**Issue by s4m0ur41** [pwnlandia/mhn#754]
Hi there,
First of all thank you to share your work. Second I am a beginner so sorry in advance if I did not search properly in issues section.
I followed install instructions and at the services verification steps I miss the "mhn" ones ?

xxxxx@xxxxxxx:/var/log/mhn$ sudo supervisorctl status
geoloc                           RUNNING   pid 1941, uptime 0:00:48
honeymap                         RUNNING   pid 1942, uptime 0:00:48
hpfeeds-broker                   RUNNING   pid 1943, uptime 0:00:48
mnemosyne                        RUNNING   pid 1940, uptime 0:00:48
xxxxx@xxxxxxx:/var/log/mhn$

Any help would be gladly appreciated.
Have a nice day

**Comment by s4m0ur41** [comment]
After another tour I have bee able to look at https://github.com/pwnlandia/mhn/issues/354.
I did not find the nhm.db mentionned.
I try to ran the ./install_mhnserver.sh but no success.

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 5, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/core.py", line 25, in <module>
    from .forms import LoginForm, ConfirmRegisterForm, RegisterForm, \
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_security/forms.py", line 15, in <module>
    from flask_wtf import Form as BaseForm
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/opt/mhn/env/local/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
**ImportError: cannot import name url_encode**

Thank you

**Comment by ancheng2017** [comment]
您需要更新requirements.txt文件并将Werkzeug库锁定为0.16.1

**Comment by JFCCoding12** [comment]
update the server/requirements.txt and included at the top werkzeug==0.16.1

**Comment by s4m0ur41** [comment]
Thank you very much Clear2020 and JFCCoding12. Every fine is fine now,
