### ISSUE TITLE
Error during fresh install: "Obtaining evnet-dev "

### ISSUE THREAD

**Issue by icepaule** [pwnlandia/mhn#761]
Hello guys,
looks like a fantastic tool, but I just can't install it.
I started a fresh and clean install but got below errors bevore the install script aborted. Could you please help me fixing this?

Thx a lot
Marcus

_+ pip install -e git+https://github.com/pwnlandia/evnet.git#egg=evnet-dev
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining evnet-dev from git+https://github.com/pwnlandia/evnet.git#egg=evnet-dev
  Cloning https://github.com/pwnlandia/evnet.git to ./env/src/evnet-dev
  Running command git clone -q https://github.com/pwnlandia/evnet.git /opt/hpfeeds/env/src/evnet-dev
    ERROR: Command errored out with exit status 1:
     command: /opt/hpfeeds/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/hpfeeds/env/src/evnet-dev/setup.py'"'"'; __file__='"'"'/opt/hpfeeds/env/src/evnet-dev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /opt/hpfeeds/env/src/evnet-dev/
    Complete output (22 lines):
    Downloading https://pypi.python.org/packages/source/d/distribute/distribute-0.6.15.tar.gz
    Extracting in /tmp/tmpg3k7jffl
    Traceback (most recent call last):
      File "/opt/hpfeeds/env/src/evnet-dev/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpfeeds/env/src/evnet-dev/setup.py", line 2, in <module>
        distribute_setup.use_setuptools()
      File "/opt/hpfeeds/env/src/evnet-dev/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/opt/hpfeeds/env/src/evnet-dev/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/opt/hpfeeds/env/src/evnet-dev/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/opt/hpfeeds/env/src/evnet-dev/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
root@piHoney:/opt/mhn#_

**Comment by d1str0** [comment]
Strange. Will look into this. Thanks.

**Comment by icepaule** [comment]
Hi @d1str0, thank YOU.  :-)

**Comment by d1str0** [comment]
What OS are you installing on and what hardware? Is this a cloud server or personal hardware?

**Comment by H4y0** [comment]
> What OS are you installing on and what hardware? Is this a cloud server or personal hardware?

Ubuntu 16.04 i guess,because i met same error
