### ISSUE TITLE
Import email_validator error. Fresh Ubuntu install.

### ISSUE THREAD

**Issue by cri57ian** [pwnlandia/mhn#766]
The install script used to work frist time, no problem. Did it a couple of times already errorless. but since yesterday, when i try to create the MHN server i get this error - i already tried pip install email_validator but did not work :

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 5, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_security/core.py", line 25, in <module>
    from .forms import LoginForm, ConfirmRegisterForm, RegisterForm, \
  File "/opt/mhn/env/lib/python2.7/site-packages/flask_security/forms.py", line 68, in <module>
    email_validator = Email(message='INVALID_EMAIL_ADDRESS')
  File "/opt/mhn/env/lib/python2.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.

Thanks in advance.

**Comment by d1str0** [comment]
Yup. Literally noticed this myself about 30 minutes ago. Easy fix. Will merge it shortly.

**Comment by cri57ian** [comment]
Ty VM. u're a star

**Comment by d1str0** [comment]
Should be good now. You'll have to pull the latest code.

**Comment by cri57ian** [comment]
Thank you. Testing and closing.

**Comment by d1str0** [comment]
Let me know if it works :)

**Comment by cri57ian** [comment]
like a charm.
