### ISSUE TITLE
Install failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by aseigler** [pwnlandia/mhn#783]
Clean OS install, had multiple people try, same results with 16.04.  Spotted some earlier similar-ish looking issues related to GeoLite2 databases but I am seeing those files in the root of the /opt folder.

Everything looks good before this point, here's the end leading up to the failure.

```bash
DONE installing python virtualenv
+ mkdir -p /var/log/mhn
+ cd /opt/mhn/server/
+ echo ===========================================================
===========================================================
+ echo '  MHN Configuration'
  MHN Configuration
+ echo ===========================================================
===========================================================
+ python generateconfig.py
config.py already exists
+ echo -e '\nInitializing database, please be patient. This can take several minutes'

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 42, in <module>
    from mhn.ui.views import ui
  File "/opt/mhn/server/mhn/ui/views.py", line 10, in <module>
    from mhn.ui.utils import get_flag_ip, get_sensor_name
  File "/opt/mhn/server/mhn/ui/utils.py", line 10, in <module>
    import geoip2.database
  File "/opt/mhn/env/lib/python2.7/site-packages/geoip2/database.py", line 9, in <module>
    import maxminddb
  File "/opt/mhn/env/lib/python2.7/site-packages/maxminddb/__init__.py", line 25
    database: Union[AnyStr, int, os.PathLike, IO], mode: int = MODE_AUTO
            ^
SyntaxError: invalid syntax

```

**Comment by 123gpg321** [comment]
seeing same as above, help

**Comment by 123gpg321** [comment]
maxminddb-1.5.2.tar.gz - newest version of this lib is broken @aseigler
