### ISSUE TITLE
Issue during installation on Ubuntu 16.04.7 LTS

### ISSUE THREAD

**Issue by destructiveresearchlabs** [pwnlandia/mhn#807]
I can't seem to get this working, I've already tried both [Issue #431](https://github.com/pwnlandia/mhn/issues/431) and [Issue #433](https://github.com/pwnlandia/mhn/issues/433) but can't seem to get this working. Any help is greatly appreciated. 
```
++ export PS1
++ alias pydoc
++ true
++ hash -r
+ python /opt/hpfeeds/broker/add_user.py mnemosyne b3bb7ccd177e427e94a7d32a7dc0e2a2 '' amun.events,conpot.events,thug.events,beeswarm.hive,dionaea.capture,dionaea.connections,thug.files,beeswarn.feeder,cuckoo.analysis,kippo.sessions,cowrie.sessions,glastopf.events,glastopf.files,mwbinary.dionaea.sensorunique,snort.alerts,wordpot.events,p0f.events,suricata.events,shockpot.events,elastichoney.events,drupot.events,agave.events
/opt/hpfeeds/env/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
Traceback (most recent call last):
  File "/opt/hpfeeds/broker/add_user.py", line 29, in <module>
    res = client.hpfeeds.auth_key.update({"identifier": ident}, {"$set": rec}, upsert=True)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/collection.py", line 3327, in update
    write_concern, collation=collation)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/collection.py", line 870, in _update_retryable
    _update, session)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1497, in _retryable_write
    with self._tmp_session(session) as s:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1829, in _tmp_session
    s = self._ensure_session(session)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/topology.py", line 488, in get_server_session
    None)
  File "/opt/hpfeeds/env/lib/python2.7/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 60830f3069771e0244729046, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>
root@pbx:/opt/mhn#
```
```
root@pbx:/opt/mhn# supervisorctl restart all
hpfeeds-logger-json: stopped
geoloc: stopped
mhn-collector: stopped
honeymap: stopped
mhn-uwsgi: stopped
mhn-celery-beat: stopped
geoloc: ERROR (spawn error)
hpfeeds-logger-json: started
hpfeeds-broker: ERROR (spawn error)
mnemosyne: ERROR (spawn error)
mhn-celery-worker: ERROR (spawn error)
mhn-celery-beat: started
mhn-uwsgi: started
mhn-collector: started
honeymap: started
root@pbx:/opt/mhn# supervisorctl status
geoloc                           FATAL     Exited too quickly (process log may have details)
honeymap                         RUNNING   pid 32014, uptime 0:00:36
hpfeeds-broker                   FATAL     Exited too quickly (process log may have details)
hpfeeds-logger-json              RUNNING   pid 32012, uptime 0:00:36
mhn-celery-beat                  RUNNING   pid 32007, uptime 0:00:36
mhn-celery-worker                FATAL     Exited too quickly (process log may have details)
mhn-collector                    STARTING
mhn-uwsgi                        RUNNING   pid 32011, uptime 0:00:36
mnemosyne                        FATAL     Exited too quickly (process log may have details)
root@pbx:/opt/mhn#
```

**Comment by destructiveresearchlabs** [comment]
A fresh installation resulted in a successful installation.
