### ISSUE TITLE
Conpot - "Address already in use"

### ISSUE THREAD

**Issue by rrgahan** [pwnlandia/mhn#824]
I am running amun, conpot, and elastichoney on a server. Per [this wiki](https://github.com/pwnlandia/mhn/wiki/Running-Multiple-Honeypots-on-the-same-server), there shouldn't be any port conflicts. However, conpot is stuck in a startup loop, with the following log repeated numerous times:

```
  MushMush Foundation

/opt/conpot/env/lib/python2.7/site-packages/gevent/builtins.py:96: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  result = _import(*args, **kwargs)
2021-11-02 12:08:44,015 Config file found!
2021-11-02 12:08:44,017 Starting Conpot using template: /opt/conpot/env/src/conpot-dev/conpot/templates/default
2021-11-02 12:08:44,017 Starting Conpot using configuration found in: /opt/conpot/conpot.cfg
WARNING:conpot.utils.ext_ip:Could not fetch public ip from http://www.telize.com/ip
2021-11-02 12:08:44,434 Could not fetch public ip from http://www.telize.com/ip
2021-11-02 12:08:44,640 Fetched xxx.xxx.xxx.xxx as external ip.
ERROR:conpot.protocols.modbus.modbus_server:'module' object has no attribute 'REPORT_SLAVE_ID'
2021-11-02 12:08:44,644 'module' object has no attribute 'REPORT_SLAVE_ID'
2021-11-02 12:08:44,645 Found and enabled ('modbus', <class conpot.protocols.modbus.modbus_server.ModbusServer at 0x7fe9d5e44280>) protocol.
2021-11-02 12:08:44,648 Conpot S7Comm initialized
2021-11-02 12:08:44,648 Found and enabled ('s7comm', <class 'conpot.protocols.s7comm.s7_server.S7Server'>) protocol.
2021-11-02 12:08:44,650 Found and enabled ('http', <class 'conpot.protocols.http.web_server.HTTPServer'>) protocol.
2021-11-02 12:08:44,652 Found and enabled ('snmp', <class 'conpot.protocols.snmp.snmp_server.SNMPServer'>) protocol.
2021-11-02 12:08:44,654 Conpot Bacnet initialized using the /opt/conpot/env/src/conpot-dev/conpot/templates/default/bacnet/bacnet.xml template.
2021-11-02 12:08:44,655 Found and enabled ('bacnet', <class 'conpot.protocols.bacnet.bacnet_server.BacnetServer'>) protocol.
2021-11-02 12:08:44,657 IPMI BMC initialized.
2021-11-02 12:08:44,658 Conpot IPMI initialized using /opt/conpot/env/src/conpot-dev/conpot/templates/default/ipmi/ipmi.xml template
2021-11-02 12:08:44,658 Found and enabled ('ipmi', <class 'conpot.protocols.ipmi.ipmi_server.IpmiServer'>) protocol.
2021-11-02 12:08:44,661 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2021-11-02 12:08:44,661 Class    22/0x0016, Instance   1, Attribute     2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2021-11-02 12:08:44,662 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2021-11-02 12:08:44,663 Class    22/0x0016, Instance   1, Attribute     3 <== [{'class': 22}, {'instance': 1}, {'attribute': 3}]
2021-11-02 12:08:44,664 Class    22/0x0016, Instance   1, Attribute     2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2021-11-02 12:08:44,664 Class    22/0x0016, Instance   1, Attribute     1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2021-11-02 12:08:44,665 Found and enabled ('enip', <class 'conpot.protocols.enip.enip_server.EnipServer'>) protocol.
2021-11-02 12:08:44,666 No proxy template found. Service will remain unconfigured/stopped.
2021-11-02 12:08:44,666 Modbus server started on: ('0.0.0.0', 502)
2021-11-02 12:08:44,667 S7Comm server started on: ('0.0.0.0', 102)
2021-11-02 12:08:44,668 HTTP server started on: ('0.0.0.0', 80)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/opt/conpot/env/src/conpot-dev/conpot/protocols/http/web_server.py", line 36, in start
    self.cmd_responder = CommandResponder(host, port, self.template, os.path.join(self.template_directory, 'http'))
  File "/opt/conpot/env/src/conpot-dev/conpot/protocols/http/command_responder.py", line 1102, in __init__
    self.httpd = SubHTTPServer((host, port), HTTPServer, template, docpath)
  File "/opt/conpot/env/src/conpot-dev/conpot/protocols/http/command_responder.py", line 976, in __init__
    BaseHTTPServer.HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/opt/conpot/env/lib/python2.7/site-packages/gevent/_socketcommon.py", line 563, in bind
    return self._sock.bind(address)
error: [Errno 98] Address already in use
2021-11-02T16:08:44Z <Greenlet at 0x7fe9d289b050: <bound method HTTPServer.start of <conpot.protocols.http.web_server.HTTPServer object at 0x7fe9d374f950>>('0.0.0.0', 80)> failed with error

2021-11-02 12:08:44,896 SNMP server started on: ('0.0.0.0', 161)
2021-11-02 12:08:44,899 Bacnet server started on: ('0.0.0.0', 47808)
2021-11-02 12:08:44,900 IPMI server started on: ('0.0.0.0', 623)
2021-11-02 12:08:44,900 handle server PID [ 3929] running on ('0.0.0.0', 44818)
2021-11-02 12:08:44,901 handle server PID [ 3929] responding to external done/disable signal in object 140642234639936
2021-11-02 12:08:44,902 Serving TCP/IP:     1, UDP/IP:     0, w/ latency:   0.100s, timeout:   0.200s (w/NO idle service)
2021-11-02 12:08:44,902 connecting to 209.177.158.146:10000
ERROR:root:Stopping because <Greenlet at 0x7fe9d289b050: <bound method HTTPServer.start of <conpot.protocols.http.web_server.HTTPServer object at 0x7fe9d374f950>>('0.0.0.0', 80)> died: [Errno 98] Address already in use
2021-11-02 12:08:44,903 Stopping because <Greenlet at 0x7fe9d289b050: <bound method HTTPServer.start of <conpot.protocols.http.web_server.HTTPServer object at 0x7fe9d374f950>>('0.0.0.0', 80)> died: [Errno 98] Address already in use
```

DId something change, where there is now a port conflict between two of these sensors? 

The most recent data I have from conpot is from 10/20.

**Comment by rrgahan** [comment]
Any updates on this?
