### ISSUE TITLE
Failing to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by m0untain04** [pwnlandia/mhn#839]
Hello. I am currently trying to install MHN on my VPS, but I am experiencing some problems.

I've managed to modify some of the files to "bypass" the python errors and got to the initdatabase.py.
But it's giving me some errors..

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/home/mhn-hn/mhn/server/mhn/__init__.py", line 42, in <module>
    from mhn.ui.views import ui
  File "/home/mhn-hn/mhn/server/mhn/ui/views.py", line 10, in <module>
    from mhn.ui.utils import get_flag_ip, get_sensor_name
  File "/home/mhn-hn/mhn/server/mhn/ui/utils.py", line 15, in <module>
    geoip2_reader = geoip2.database.Reader(MHN_SERVER_HOME+'/../../GeoLite2-City.mmdb')
  File "/home/mhn-hn/mhn/env/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/home/mhn-hn/mhn/env/lib/python2.7/site-packages/maxminddb/__init__.py", line 46, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/home/mhn-hn/mhn/env/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, "rb") as db_file:

Maybe you guys can help me.

Thanks in advance !

**Comment by wrharding** [comment]
There are a number of issues regarding Ubuntu 20.04 and Python 3/2.7 interop. Please see #779 and #793 for potential work arounds. As always, pull requests are welcome.
