### ISSUE TITLE
Error during setup: ImportError: No module named collections_abc

### ISSUE THREAD

**Issue by HollywoodMarks** [pwnlandia/mhn#847]
Received the following error during setup on Ubuntu 18, when trying to install the MHN server:

+ /usr/local/bin/virtualenv -p /usr/bin/python env
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/run/__init__.py", line 7, in <module>
    from ..app_data import make_app_data
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/app_data/__init__.py", line 12, in <module>
    from .read_only import ReadOnlyAppData
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/app_data/read_only.py", line 3, in <module>
    from virtualenv.util.lock import NoOpFileLock
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/util/lock.py", line 13, in <module>
    from virtualenv.util.path import Path
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/util/path/__init__.py", line 3, in <module>
    from ._pathlib import Path
  File "/usr/local/lib/python2.7/dist-packages/virtualenv/util/path/_pathlib/__init__.py", line 14, in <module>
    from pathlib2 import Path
  File "/usr/local/lib/python2.7/dist-packages/pathlib2/__init__.py", line 26, in <module>
    from six.moves.collections_abc import Sequence
ImportError: No module named collections_abc

**Comment by HollywoodMarks** [comment]
/opt/mhn/server$ virtualenv --version
virtualenv 20.13.1 from /usr/local/lib/python2.7/dist-packages/virtualenv/__init__.pyc

**Comment by GryphonInfoSec** [comment]
This is due to an older version of virtualenv requirement. pip version breaks the install.  do a pip uninstall and use apt instead.
sudo apt install python-virtualenv
