### ISSUE TITLE
mhn install fails on linux ubuntu 18.04.6：No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'

### ISSUE THREAD

**Issue by yunzhongzhilong** [pwnlandia/mhn#848]
Hello
i am trying install mhn on fresh install of ubuntu 18.04.6
Get an error.

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 42, in <module>
    from mhn.ui.views import ui
  File "/opt/mhn/server/mhn/ui/views.py", line 10, in <module>
    from mhn.ui.utils import get_flag_ip, get_sensor_name
  File "/opt/mhn/server/mhn/ui/utils.py", line 15, in <module>
    geoip2_reader = geoip2.database.Reader(MHN_SERVER_HOME+'/../../GeoLite2-City.mmdb')
  File "/opt/mhn/env/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/opt/mhn/env/lib/python2.7/site-packages/maxminddb/__init__.py", line 46, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/opt/mhn/env/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, "rb") as db_file:
IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'

**Comment by d1str0** [comment]
I recommend commenting out that step of installation.
