### ISSUE TITLE
mhn install fails on linux ubuntu 18.04.7

### ISSUE THREAD

**Issue by Berwynnnn** [pwnlandia/mhn#849]

**Comment by rubenwelle** [comment]
I am having the same error with Ubuntu 16.04 (clean install)

Processing triggers for libc-bin (2.23-0ubuntu11.3) ...
+ pip install --upgrade pip
The directory '/home/captain811/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/captain811/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a3/50/c4d2727b99052780aad92c7297465af5fe6eec2dbae490aa9763273ffdc1/pip-22.3.1.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 580kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-R8hy6p/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-R8hy6p/pip/
You are using pip version 8.1.1, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by devel1988** [comment]
same error here
