### ISSUE TITLE
mnemosyne fails to start

### ISSUE THREAD

**Issue by exqua** [pwnlandia/mhn#850]
Hi, I have an issue with mnemosyne not wanting to start.

Hopefully someone can help me out.

supervisorctl status
conpot                           STARTING
cowrie                           RUNNING   pid 678, uptime 0:04:16
dionaea                          RUNNING   pid 671, uptime 0:04:16
geoloc                           RUNNING   pid 674, uptime 0:04:16
honeymap                         RUNNING   pid 686, uptime 0:04:16
hpfeeds-broker                   RUNNING   pid 672, uptime 0:04:16
mhn-celery-beat                  RUNNING   pid 670, uptime 0:04:16
mhn-celery-worker                RUNNING   pid 1152, uptime 0:00:21
mhn-collector                    RUNNING   pid 682, uptime 0:04:16
mhn-uwsgi                        RUNNING   pid 676, uptime 0:04:16
mnemosyne                        FATAL     Exited too quickly (process log may have details)
snort                            RUNNING   pid 721, uptime 0:04:12

cat mnemosyne.err
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'
Traceback (most recent call last):
  File "runner.py", line 18, in <module>
    import gevent
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/opt/mnemosyne/env/lib/python2.7/site-packages/gevent/hub.py", line 11, in <module>
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
ValueError: invalid literal for int() with base 10: 'post0'

**Comment by exqua** [comment]
I removed the greenlet_version from hub.py and now its working:

greenlet_version = getattr(greenlet, '__version__', None)
if greenlet_version:
    greenlet_version_info = [int(x) for x in greenlet_version.split('.')]
if not greenlet_version or greenlet_version_info[:3] < [0, 3, 2]:
    raise ImportError('''Your version of greenlet (%s) is too old (required >= 0.3.2)
             You can get a newer version of greenlet from http://pypi.python.org/pypi/greenlet/''' % (greenlet_version, ))
