### ISSUE TITLE
Error in python file generateconfig.py !

### ISSUE THREAD

**Issue by AbdelrahmanEmad12** [pwnlandia/mhn#854]
+ echo '  MHN Configuration'
  MHN Configuration
+ echo ===========================================================
===========================================================
+ python generateconfig.py
Traceback (most recent call last):
  File "generateconfig.py", line 184, in <module>
    generate_config()
  File "generateconfig.py", line 32, in generate_config
    pub_ip = get_pub_ip()
  File "generateconfig.py", line 21, in get_pub_ip
    sock = urlopen('http://icanhazip.com/')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1208, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1178, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 452, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

**Comment by wrharding** [comment]
This looks like you have a firewall blocking outbound connections to http://icanhazip.com, which MHN uses to query you external IP initially. Your external IP is used as the default server address, unless you choose to change it in the step immediately following what you've posted.
